### ISSUE TITLE
Introduce an endpoint to serve user avatars

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#3089]

**Comment by davidcmoulton** [comment]
```
curl --request POST \
  --url 'https://dev-sqa2k3wwnhpxk36d.eu.auth0.com/oauth/token' \
  --header 'content-type: application/json' \
  --data '{ "grant_type":"client_credentials", "client_id":"...", "client_secret":"...", "audience":"https://dev-sqa2k3wwnhpxk36d.eu.auth0.com/api/v2/" }'
```

**Comment by giorgiosironi** [comment]
How to add a permission to a Machine to Machine application through the Auth0 CLI `tenant.yaml`:
```
clientGrants:
  - client_id: Sciety
    audience: https://dev-sqa2k3wwnhpxk36d.eu.auth0.com/api/v2/
    scope:
      - read:users
      - read:clients
```
(this still has the `audience` hardcoded for the dev tenant)
