### ISSUE TITLE
Retain the original intent of Sass compilation in the light of Sass implementation changes

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#3564]
See #3446 for context and problem setting.

This ticket is an experiment of updating our sass code so that, in the light of the sass implementation changes, declarations that follow nested rules either:
- will be moved up, so the order of the rules in the sass code is the order that the css would have been compiled to anyway, before the sass implementation changes
i.e.:
```scss
// Sass:
.card {
  display: block;
  
  h2 {
    font-size: large;
  }
    border: 1px solid black;
}
```

will be changed to:

```scss
// Sass:
.card {
  display: block;
  border: 1px solid black;
  
h2 {
    font-size: large;
  }
}
```

or
- will be scoped so that the order of the declaration is expressed more intentionally in the sass.
i.e.
```scss
// Sass:
.card {
  display: block;
  
  h2 {
    font-size: large;
  }
    border: 1px solid black;
}
```

will be changed to:
```scss
// Sass:
.card {
  display: block;
  
  h2 {
    font-size: large;
  }

  & {
    border: 1px solid black;
  }
}
```

The first step for trying to see the wood for the trees is changing the linter to insist on declarations before empty at-rule includes. This will hopefully catch a lot of the situations we care about. EDIT: See 46de77a.
